language: java
sudo: true
install: true

before_install: |
  # install awscli v2 if not available
  if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi

services:
  - docker

branched:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
    - '$HOME/docker'

env:
  global:
    - APP_NAME: "cicd-sample-app"
    - S3_BUCKET: "sample-travisci-artifact"
    - WORK_DIR: out

jobs:
  include:
    - stage: Maven Test
      jdk: openjdk17
      script: |
        mvn clean test

    - stage: Maven Build
      jdk: openjdk17
      script: |
        mvn clean package -DskipTests
        mkdir $WORK_DIR
        mv ./target $WORK_DIR
        cp ./Dockerfile $WORK_DIR
      after_script: |
        aws s3 sync $WORK_DIR s3://$S3_BUCKET/$TRAVIS_BUILD_ID/$WORK_DIR

    - stage: Docker Build & Deploy
      before_script: |
        aws s3 sync s3://$S3_BUCKET/$TRAVIS_BUILD_ID/$WORK_DIR $WORK_DIR
        cd $WORK_DIR
      script: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 348951190761.dkr.ecr.ap-northeast-2.amazonaws.com
        TAG="$(echo $TRAVIS_COMMIT | cut -c -7)"
        TAGGED_IMAGE="348951190761.dkr.ecr.ap-northeast-2.amazonaws.com/$APP_NAME"
        IMAGE="${TAGGED_IMAGE}:${TAG}"
        echo 'image:' $IMAGE
        docker build -t "$IMAGE" .
        docker push "${IMAGE}"

    - stage: Manifest Deploy
      script: |
        curl -sSL -o ./yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x ./yq

        git clone -b main https://misoboy:${GITHUB_TOKEN}@github.com/cnalabs/cicd-sample-helm.git /tmp/helm
        cd /tmp/helm
    
        V_TIMESTAMP=$(date +%s)
        ./yq e --inplace ".timestamp = \"$V_TIMESTAMP\"" values.yaml
        ./yq e --inplace ".image.repository = \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME\"" values.yaml
        ./yq e --inplace ".image.tag = \"$(echo $TRAVIS_COMMIT | cut -c -7)\"" values.yaml
    
        git config user.email "misoboy.kor@gmail.com"
        git config user.name "misoboy.kor"
        git add -u
        git commit -m "Update Image Tag: $$APP_NAME:$(echo $TRAVIS_COMMIT | cut -c -7)"
        git push origin main

    - stage: Call Tekton Pipeline
      script: |
        curl --location 'https://event.slabs.kr' \
          --header 'Content-Type: application/json' \
            --data '{
          "repository": {
            "url": "https://github.com/cnalabs/cicd-sample-helm.git",
            "revision": "main"
          }
        }'
