version: 0.0
os: linux
files:
  - source: ./cicd-sample-app-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: root
    group: root
    mode: 700
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
