version: 2.1
defaults:
  envrionments:
    APP_NAME: cicd-sample-app

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  docker: circleci/docker@2.2.0
  jq: circleci/jq@2.2.0
  aws-ecr: circleci/aws-ecr@8.2.1
  rnikkei-yq: nikkei/rnikkei-yq@0.0.3

jobs:
  BuildAndTest:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name : Maven Test
          command : |
            chmod +x mvnw
            ./mvnw -e clean test

      - run:
          name : Maven Build
          command : |
            chmod +x mvnw
            ./mvnw -e clean package -DskipTests
            mkdir deploy
            cp ./target/*.jar ./deploy
            cp ./Dockerfile ./deploy

      - save_cache:
          paths:
            - ~/.mvn
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - deploy


  DockerBuild:
    machine: true
    steps:
      - attach_workspace:
          at: /home/circleci/project

      - aws-cli/install:
          override-installed: false 
          disable-aws-pager: true 

      - aws-ecr/ecr-login

      - docker/build:
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME 
          dockerfile: ./deploy/Dockerfile 
          tag: $(echo $CIRCLE_SHA1 | cut -c -7)

      - docker/push:
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME  
          tag: $(echo $CIRCLE_SHA1 | cut -c -7)

  ManifestDeploy:
    machine: true
    steps:
      - jq/install
      - aws-cli/install:
          override-installed: false 
          disable-aws-pager: true 

      - rnikkei-yq/install:
          arch: amd64 

      - run:
          name: Manifest Deploy
          command: |
            echo "Argo Workflow call process..."
            git clone -b main https://misoboy:${GITHUB_TOKEN}@github.com/cnalabs/cicd-sample-helm.git /tmp/helm
            cd /tmp/helm
            
            V_TIMESTAMP=$(date +%s)
            yq e --inplace ".timestamp = \"$V_TIMESTAMP\"" values.yaml
            yq e --inplace ".imageRepo = \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME\"" values.yaml
            yq e --inplace ".imageTag = \"$(echo $CIRCLE_SHA1 | cut -c -7)\"" values.yaml
            
            git config user.email "misoboy.kor@gmail.com"
            git config user.name "misoboy.kor"
            git add -u
            git commit -m "Update Image Tag: $APP_NAME:$TAG"
            git push origin main

workflows:
  version: 2
  workflow:
    jobs:
      - BuildAndTest:
          filters:
            branches:
              only: main
      - DockerBuild:
          context: GITHUB_SECRET
          requires:
            - BuildAndTest
          filters:
            branches:
              only: main
      - ManifestDeploy:
          context: GITHUB_SECRET
          requires:
            - DockerBuild
          filters:
            branches:
              only: main
